version: '3.8'

services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "ftp_sender"

    networks:
      - dwld
    volumes:
      - ../ftp_sender.yaml:/var/ftp_sender.yaml
      - ../ftp_sender.db:/var/ftp_sender.db


networks:
  dwld:
    driver: bridge
