version: '3.8'

services:
  ftp_sender:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "ftp_sender"

    networks:
      - dwld
    volumes:
      - /ftp_sender.yaml:/app/ftp_sender.yaml


networks:
  dwld:
    driver: bridge
